config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'zadankai#home'
  get 'zadankai/about'
  get 'users/index'

  get 'users/show'

  mount Ckeditor::Engine => '/ckeditor'
  get 'projects/readyfor'
  post 'projecs/pay' => 'projects#pay'
  get 'projects/new'

  devise_for :users, :controllers => {
    :sessions      => "users/sessions",
    :registrations => "users/registrations",
    :passwords     => "users/passwords",
    :omniauth_callbacks => "users/omniauth_callbacks"
  }
  
  resources :users
  
  resources :projects do
    resources :comments
    resources :conferences do
      resources :opinions
    end
  end
  
  resources :relationships, only: [:create, :destroy]

  resources :projects do
    member do
      get :joined_projects
    end
  end
  
  resources :users do
    member do
      get :joiner_user
    end
  end
  

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :conferences
  
  #relationships
  has_many :joining_relationships, class_name:  "Relationship",
                                    foreign_key: "joined_project_id",
                                    dependent:   :destroy
  has_many :joiner_users, through: :joining_relationships, source: :joiner_user
  
  validates :project_name, :category, presence: true
  validates :period_date, presence: true
  
  mount_uploader :main_image, ImageUploader
  mount_uploader :movie, MovieUploader


  
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :project_owner, only: [:edit, :update, :destroy]
  require 'date'
  
  def readyfor
  end
  
  def index
    @projects = Project.order(created_at: :desc)
    #検索
    @q = Project.search(params[:q])
    @searchedProjects = @q.result(distinct: true)
  end
  
  def charge
    webpay = WebPay.new('test_secret_eHn4TTgsGguBcW764a2KA8Yd')
    webpay.charge.create(
    amount: 400,
    currency: "jpy",
    card: "tok_01p4zyfJV9K4gOX"
)
  end
  
  def search
    @q = Project.search(params[:q])
    @projects1 = @q.result(distinct: true)
  end

  def new
    @project = Project.new
  end
  
  def create
    @project = current_user.projects.build(project_params)
    if @project.save
      flash[:success] = "新規プロジェクトを作成しました"
      redirect_to projects_path
    else
      render 'zadankai/home'
    end
  end
  
  def show
    @project = Project.find(params[:id])
    @project_title = @project.project_name
    # 参加しているユーザー
    @users = @project.joiner_users.group('joiner_user_id')
    # 参加しているユーザーがいる場合はそのUserを取得
    if @users.any?
    @joinerUser = @project.joiner_users.find(@users)
    end
    
    @d1 = Time.zone.now
    if @project.period_date.present?
    @d2 = (@project.period_date - @d1).to_i / 1.day
    end
  end
  
  def edit
    @project = Project.find(params[:id])
  end
  
  def update
    @project = Project.find(params[:id])
    if @project.update(edit_project_params)
      flash[:success] = "Your project was updated!"
      redirect_to @project
    else
      render 'edit'
    end
  end

  def destroy
    @project = current_user.projects.find_by(id: params[:id])
    return redirect_to root_url if @project.nil?
    @project.destroy
    flash[:success] = "Project deleted"
    redirect_to projects_path
  end
  
  
  
  private
  def project_params
    params
      .require(:project).permit(:project_name, :brand_name, :category, :main_image, :movie, :youtube_url, :description, :aim_money, :period_date)
      
  end
  
  def edit_project_params
    params.require(:project).permit(:project_name, :brand_name, :category, :main_image, :movie, :youtube_url, :description, :aim_money, :period_date)
  end
  
  #project のオーナーかどうか判断
  def project_owner
    @project = Project.find(params[:id])
    unless @project.user_id == current_user.id
      flash[:notice] = 'Access denied as you are not owner of this project'
      redirect_to projects_path
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
    
  def embed(youtube_url)
    if @project.youtube_url.present?
        youtube_id = youtube_url.split("=").last
        content_tag(:iframe, nil, src: "//www.youtube.com/embed/#{youtube_id}")
    end
  end
  
end

app/views/projects/_conference_list.html.erb
    <h4>開かれてる座談会</h4>
    <% if @project.conferences.present? %>
      <div class="panel panel-info">
        <% @project.conferences.order("created_at desc").each do |conference| %>
          <div class="panel-heading">
            <p><%= conference.created_at.to_s(:default) %></p>
          </div>
          <div class="panel-body">
            <p><%= link_to conference.title, project_conference_path(@project, conference) %></p>
          </div>
        <% end %>
      </div>
            
    <% else current_user == @project.user %>
      <p>現在ひらかれている座談会はありません</p>
    <% end %>

app/views/projects/_joined_list.html.erb
<div class="container">
  <div class="container-inner inner-default clearfix">
    <% projects_lists.each do |project| %>
      <div class="item-box">
        <div class="image">
          <div class="img-wrap">
            <% if project.main_image.present? %>
              <%= link_to image_tag(project.main_image.url , alt: project.project_name), project %>
            <% else %>
              <%= link_to image_tag("no-image.png" , alt: project.project_name), project %>
            <% end %>
          </div>
        </div>
        <div class="detail">
          <p class="title">
            <%= project.project_name %>
          </p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/_list.html.erb
<div class="container">
  <div class="container-inner inner-default clearfix">
    <% projects.order("created_at desc").each do |project| %>
      <div class="item-box">
        <div class="image">
          <div class="img-wrap">
            <% if project.main_image.present? %>
              <%= link_to image_tag(project.main_image.url , alt: project.project_name), project %>
            <% else %>
              <%= link_to image_tag("no-image.png" , alt: project.project_name), project %>
            <% end %>
          </div>
        </div>
        <div class="detail">
          <p class="title">
            <%= project.project_name %>
          </p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/_list_users.html.erb
<div class="container">
  <div class="container-inner inner-default clearfix">
    <% projects.order("created_at desc").each do |project| %>
      <div class="item-box-mini">
        <div class="image">
          <div class="img-wrap">
            <% if project.main_image.present? %>
              <%= link_to image_tag(project.main_image.url , alt: project.project_name), project %>
            <% else %>
              <%= link_to image_tag("no-image.png" , alt: project.project_name), project %>
            <% end %>
          </div>
        </div>
        <div class="detail">
          <p class="title">
            <%= project.project_name %>
          </p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/edit.html.erb
<h1 style="text-align: center;">プロジェクト編集</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@project) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
          <%= f.label :category %>
          <%= f.select :category,
              ["アート","写真","プロダクト","スポーツ","お笑い","ファッション","ダンス","演劇・舞台","映像・映画","本・漫画","旅行","ビジネス","テクノロジー","社会貢献","その他"], { include_blank: '選択してください'} , class: "form-control" %></br>
                  
          <%= f.label :brand_name, "ブランド名" %>
          <%= f.text_field :brand_name, class: "form-control" %><br/>
          
          <%= f.label :project_name, "プロジェクト名" %>
          <%= f.text_field :project_name, class: "form-control" %>
          
          <%= f.label :period_date, "プロジェクト終了予定日" %>
          <div class='input-group date datepicker'>
          <%= f.text_field :period_date, :placeholder => "(例)2015-01-01-12:00", class: 'form-control datepicker' %>
          <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
          </div><br/>
    
          <%= f.label :main_image, "メイン画像" %>
          <%= f.file_field :main_image, class: "form-control" %>
    
          <%= f.label :youtube_url, "Youtube動画 URL" %>
          <%= f.text_field :youtube_url, :placeholder => "https://www.youtube.com/watch?v=xxxxxxxxxxx" ,class: "form-control" %></br>
          
          <%= f.label :description, class: 'control-label' %>
          <%= f.cktext_area :description, class: 'form-control' %></br>
          <%= f.submit "プロジェクト情報の更新!", class: "btn btn-large btn-primary form-control" %>
          
      <% end %>
    </div>
        
</div>

app/views/projects/index.html.erb
<div class="container">
  <div class="col-xs-6 col-xs-offset-3">
    <form class="form-inline">
      <div class="form-group">
          <%= search_form_for @q do |f| %>
          <!-- start 特定の文字列で始まる商品名で検索 -->
          <%= f.label :project_name_cont, "フリーワードで検索する", class: "control-label"  %>
          <%= f.search_field :project_name_cont, class: "form-control" %>
          <%= f.submit "検索する", class: "btn btn-large btn-primary form-control" %>
          <% end %>
          <%= search_form_for @q do |f| %><br/>
          <!-- カテゴリーで検索 -->
          <%= f.label :category_cont, "カテゴリーから検索する", class: "control-label"  %>
          <%= f.select :category_cont,["選択してください", "アート","写真","プロダクト","スポーツ","お笑い","ファッション","ダンス","演劇・舞台","映像・映画","本・漫画","旅行","ビジネス","テクノロジー","社会貢献","その他"], class: "form-control" %>
          <%= f.submit "検索する", class: "btn btn-sm btn-primary form-control" %>
          <% end %>
          
      </div>
    </form>
  </div>
</div><br/>

<div class="container">

    <% if @q == nil %>
        <%= render 'projects/list' , projects: @projects %>
    <% else %>
        <%= render 'projects/list' , projects: @searchedProjects %>
    <% end %>
</div>
    

app/views/projects/new.html.erb
<h1 style="text-align: center;">プロジェクトを作成する</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3 "form-group"">
    <%= form_for(@project) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :category, "カテゴリー" %>
      <%= f.select :category,
              ["アート","写真","プロダクト","スポーツ","お笑い","ファッション","ダンス","演劇・舞台","映像・映画","本・漫画","旅行","ビジネス","テクノロジー","社会貢献","その他"], { include_blank: '選択してください'} , class: "form-control" %></br>
      <%= f.label :brand_name, "ブランド名" %>
      <%= f.text_field :brand_name, class: "form-control" %><br/>
      
      <%= f.label :project_name, "プロジェクト名" %>
      <%= f.text_field :project_name, :placeholder => "(例) 新感覚デニムを一からつくる！" , class: "form-control" %><br/>
      
      <%= f.label :period_date, "プロジェクト終了予定日" %>
      <div class='input-group date datepicker'>
        <%= f.text_field :period_date, :placeholder => "(例)2015-01-01-12:00", class: 'form-control datepicker' %>
      <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
      </div><br/>
      
      <%= f.label :main_image, "メイン画像" %>
      <%= f.file_field :main_image, class: "form-control" %><br/>

      <%= f.label :youtube_url, "Youtube動画 URL" %>
      <%= f.text_field :youtube_url, :placeholder => "https://www.youtube.com/watch?v=xxxxxxxxxxx" ,class: "form-control" %></br>
      
      <%= f.label :aim_money, "目標金額(¥)" %>
      <%= f.text_field :aim_money, :placeholder => "(例)1,000,000" ,class: "form-control" %><br/>
      
      <%= f.label :description, "プロジェクト詳細",  class: 'control-label' %>
      <%= f.cktext_area :description, class: 'form-control' %><br/>
      <%= f.submit "プロジェクトを投稿する！", class: "btn btn-large btn-primary form-control" %>
      
    <% end %>
  </div>
  <script type="text/javascript">
            $(function () {
                $('#datetimepicker1').datetimepicker({
                 
                });
                
            });
  </script>
</div>

app/views/projects/pay.html.erb
<div class="container">
    <h4>支払い完了</h4>
</div>

app/views/projects/readyfor.html.erb
<div id="ready-for-jumbotron">
    <div class="container">
      <h1 style="text-align: center;">Zadankai</h1>
      <p style="text-align: center;">ファンファンファン</p>
      <h3>How to start your own project?</h3><br/>
      <h2>⬇︎</h2>
    </div><!-- /.container -->
</div><!-- /.jumbotron -->

<div id="readyfor-contents" class="container">
  <h2>使い方はかんたん。<br/>
  プロジェクトを作成してスタートするだけ。</h2>
  <div class="row">
    <div class="col-md-4">
      <h4>1. プロジェクトを作成</h4>
    </div>
    <div class="col-md-4">
      <h4>2. 座談会を開催して、プロジェクトを創り上げていく。</h4>
    </div>
    <div class="col-md-4">
      <h4>3. プロジェクト完了報告！</h4>
    </div>
  </div>
  <% if user_signed_in?  %>
    <p><%= link_to "プロジェクトを作成する", projects_new_path, class: "btn btn-large btn-primary" %></p>
  <% else %>
    <p><%= link_to "まずは新規会員登録する", new_user_registration_path, class: "post btn btn-large btn-primary" %></p>
  <% end %>
 
</div>
<div id="about" class="container">
  
</div>
<div id="about-zadankai">
<div class="container">
  <div class="row">
    <div class="col-md-6">
      
    </div>
    <div class="col-md-6">
      <h2>Zadankaiとは？</h2>
      <p>こんなものを創りたい。こんなイベントを企画したい。なにか楽しいことをしたい。<br/>
      そういったあなたの心の中にある思いを形にするお手伝いをしたい。<br/>
      そんな思いから、この「Zadankai」はスタートしました。<br/>
      気軽に心の中の想いをシェアして、それに賛同してくれる仲間（ファン）に出会い、企画を実現させる。<br/>
      どんどんアイデアをシェアしよう。そのアイデアをみんなで育てて実現させよう。<br/>
      </p>
    </div>
    
  </div>
  
</div>
</div>

app/views/projects/show.html.erb
<% content_for :head do %>
  <meta name="title" content="<%=@project.project_name %>">
  <meta name="description" content="<%=@project.project_name %>に関する情報です">
<% end %>

<div class="container">
  <div class="row">
    <div class="col-sm-2 projrct-user-profile">
      <% if @project.brand_name.present? %>
      <h4><%= @project.brand_name %></h4>
      <% end %>
      <% if @project.user != nil %>
      <h4><%= @project.user.nickname  %></h4>
        <% if @project.user.remote_avatar != nil %>
          <%= image_tag(@project.user.remote_avatar , alt: @project.user.nickname) %>
        <% else %>
          <%= image_tag(@project.user.avatar.url , alt: @project.user.nickname) %>
        <% end %>
      <% end %>
      <h5>プロジェクト完了予定日</h5>
      <% if @project.period_date.present? %>
        <h5><%= @project.period_date %></h5>
        <% if @d2 >= 0 %>
        <h5>終了まであと<strong><%= @d2 %></strong>日</h5>
        <% else %>
        <h5>終了</h5>
        <% end %>
      <% end %>
      <div>
        <% if current_user == @project.user && current_user != nil %>
            <%= link_to "プロジェクトの編集", edit_project_path(@project), class: "btn btn-large btn-default" %>
        <% end %>
      </div>
    </div>
    <div class= "col-sm-7">
       <%= form_tag(action: :pay, method: :post) do %>
        <script src="https://checkout.webpay.jp/v3/" class="webpay-button" data-key="test_public_19DdUs78k2lV8PO8ZCaYX3JT" data-lang="ja"></script>
      <% end %>
      <div class="title">
        <% if current_user != nil && current_user != @project.user %>
        <%= render 'users/join_form' %>
        <% end %>
        
        <h2><%= @project.project_name %></h2>
      </div>
      <% if @project.youtube_url.present? %>
        <div class= "youtube-container">
          <%= embed(@project.youtube_url) %>
        </div>
      <% else %>
        <%= image_tag(@project.main_image) %>
      <% end %>
      <div class="fb-like" data-href="<%= "http://#{request.host+request.fullpath}" %>" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div>
      <div>
        <h3>どんなプロジェクトなの？</h3>
        <%== @project.description %>
      </div>
      <% if current_user != nil %>
      <section class="comment_form">
          <%= render 'shared/comment_form' %>
      </section>
      <% end %>
      <h3>コメント一覧</h3>
      <% if @project.comments.count == 0 %>
        <p>現在コメントはありません。</p>
      <% end %>
        <% if @project.comments.present? %>
        <% @project.comments.order("created_at asc").each do |comment| %>
        <!-- コメントがプロジェクトオーナーの場合は右表示 -->
          <% if comment.commenter == @project.user.nickname %>
            <div class="comment2-1">
              <div class="imgL">
                <% if comment.remote_avatar != nil %>
                  <p><%= image_tag(comment.remote_avatar , alt: comment.commenter) %><br/>
                  <%= comment.commenter %></p>
                <% else %>
                  <p><%= image_tag(comment.avatar , alt: comment.commenter) %><br/>
                  <%= comment.commenter %></p>
                <% end %>  
              </div>
              <div class="commentContents">  
                <p><%= simple_format comment.body %></p>  
                <p class="data"><%= comment.created_at.to_s(:default) %></p>
                <% if current_user != nil %>
                  <% if current_user.nickname == comment.commenter%>
                    <%= link_to "編集", edit_project_comment_path(@project, comment), class: "btn btn-large btn-default" %>
                    <%= link_to "削除", project_comment_path(@project, comment), method: :delete, class: "btn btn-large btn-danger", data: { confirm: "You sure?" } %>
                  <% end %>
                <% end %>
                <!--/ .commentContents-->
              </div>  
            </div><!-- .comment1-1 -->
          <% else %><!-- その他の人は左表示 -->
            <div class="comment1-1">
              <div class="imgL">
                <% if comment.remote_avatar != nil %>
                  <p><%= image_tag(comment.remote_avatar , alt: comment.commenter) %><br/>
                  <%= comment.commenter %></p>
                <% else %>
                  <p><%= image_tag(comment.avatar , alt: comment.commenter) %><br/>
                  <%= comment.commenter %></p>
                <% end %>  
              </div>
              <div class="commentContents">  
                <p><%= simple_format comment.body %></p>  
                <p class="data"><%= comment.created_at.to_s(:default) %></p>
                <% if current_user != nil %>
                  <% if current_user.nickname == comment.commenter%>
                    <%= link_to "編集", edit_project_comment_path(@project, comment), class: "btn btn-large btn-default" %>
                    <%= link_to "削除", project_comment_path(@project, comment), method: :delete, class: "btn btn-large btn-danger", data: { confirm: "You sure?" } %>
                  <% end %>
                <% end %>
                <!--/ .commentContents-->
              </div>  
            </div><!-- .comment1-1 -->
          <% end %>

       <% end %>
       <% end %>
      
    </div>  
    
    <div class="col-sm-3">
      <% if @users.any? %>
      <p>プロジェクトメンバー数: <strong><%= @users.length %></strong>人</p>
        <% @users.each do |user| %>
          <%= user.nickname %>
          <% if user.remote_avatar != nil %>
            <p><%= image_tag(user.remote_avatar, class: "icon_image" , alt: user.nickname) %></p>
          <% else %>
            <p><%= image_tag(user.avatar , class: "icon_image", alt: user.nickname) %></p>
          <% end %>
        <% end %>
      <% end %>
      
      <% if current_user == @project.user && current_user != nil %>
      <div>
          <%= link_to "座談会を開催する！" , new_project_conference_path(@project),class: "btn btn-large btn-primary" %>
      </div><br/>
      <% else %>
        <%  %>
      <% end %>
      
      <% if current_user != nil %>
        <% if @joinerUser != nil %>
          <% if @users.include? current_user %>
            <%= render 'conference_list' %>
          <% elsif current_user == @project.user %>
            <%= render 'conference_list' %>
          <% else %>
            <% # %> 
          <% end %>
        <% elsif current_user == @project.user %>
          <%= render 'conference_list' %>
        <% else %>
          <% # %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

    
  