config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'zadankai#home'
  get 'zadankai/about'
  get 'users/index'

  get 'users/show'

  mount Ckeditor::Engine => '/ckeditor'
  get 'projects/readyfor'
  post 'projecs/pay' => 'projects#pay'
  get 'projects/new'

  devise_for :users, :controllers => {
    :sessions      => "users/sessions",
    :registrations => "users/registrations",
    :passwords     => "users/passwords",
    :omniauth_callbacks => "users/omniauth_callbacks"
  }
  
  resources :users
  
  resources :projects do
    resources :comments
    resources :conferences do
      resources :opinions
    end
  end
  
  resources :relationships, only: [:create, :destroy]

  resources :projects do
    member do
      get :joined_projects
    end
  end
  
  resources :users do
    member do
      get :joiner_user
    end
  end
  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="copyright">© <%= Date.today.year %> Zadankai.com All right reserved.</div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">
    <div class="container">
        <%= link_to "Zadankai", root_path, class: "navbar-brand", id: "brand-logo" %>
        <nav>
            <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "Zadankaiとは？", zadankai_about_path  %></li>
                <% if user_signed_in? %>
                    <li>
                      <%= link_to "マイページ", user_path(current_user) %>
                    </li>
                    <li>
                      <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
                    </li>
                <% else %>
                    
                    <li>
                      <%= link_to "ログイン", new_user_session_path, :class => 'post' %>
                    </li>
                    <li>
                      <%= link_to "新規登録", new_user_registration_path, :class => 'post' %>
                    </li>
                <% end %>
            </ul>
            <ul class="nav navbar-nav navbar-left">
                <li>
                    <%= link_to "プロジェクトをはじめる", projects_readyfor_path %>
                </li>
                <li><%= link_to "プロジェクトを探す", projects_path %></li>
            </ul>
        </nav>
    </div>
    
</header>

 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <% if @project_title.present? %>
   <title><%= "#{@project_title} - Zadankai" %></title>
  <% elsif @userName.present? %>
   <title><%= "#{@userName} - Zadankai" %></title>
  <% elsif @conference_title.present? %>
   <title><%= "#{@conference_title} - Zadankai" %></title>
  <% else %>
  <title><%= 'Zadankai' %></title>
  <% end %>
  <% #meta information %>
  <%= yield :head %>
  
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <%= render partial: "layouts/header" %>
  <div class="contariner">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %> 
    <%= yield %>
  </div>
  <%= render partial: "layouts/footer" %>
  
  <!-- facebook javascript SDK -->
  <script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '1531411813822076',
      xfbml      : true,
      version    : 'v2.5'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/ja_JP/sdk.js#xfbml=1&version=v2.5&appId=915645191823908";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

</body>
</html>